# Generated by Django 6.0.6 on 2026-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_preview',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
